### ISSUE TITLE
Failed at the last step.

### ISSUE THREAD

**Issue by danish-khan-I** [AmmeySaini/Edu-Mail-Generator#1]
selected college no 2 "contra consta"
failed at the last step.
exception below
```
[*] Details Progress - 6/8Traceback (most recent call last):
  File "bot.py", line 999, in <module>
    main()
  File "bot.py", line 996, in main
    start_bot(reg_url, userEmail, allColleges[userInput], userInput + 1)
  File "bot.py", line 764, in start_bot
    EC.element_to_be_clickable((By.ID, 'inputHispanicNo'))
  File "C:\Users\danish\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\danish\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\danish\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\danish\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <input id="inputHispanicNo" name="_personalInfo.hispanic" class="portlet-form-input-radio" type="radio" value="false" aria-controls="inputRaceEthnicity100SubGroups"> is not clickable at point (584, 493). Other element would receive the click: <li class="ccc-form-element yesno">...</li>
  (Session info: chrome=84.0.4147.105)
```

**Comment by AmmeySaini** [comment]
it usually happens if your window is **minimized**, try again and this time keep the window active don't minimize it.
If still error persists we will try to replicate and fix it.

**Comment by danish-khan-I** [comment]
Is it gonna start from the beginning or it will continue from where error occurred?

**Comment by AmmeySaini** [comment]
it'll start from beginning, you can use same mail

**Comment by danish-khan-I** [comment]
I did complete the last step manually and received mail from college and verified. what's next?

**Comment by AmmeySaini** [comment]
then wait for next few hours they will send you instructions. It can take upto 72 hours depending on clg
