### ISSUE TITLE
Proxy still detected even i use the 0.2.8 version

### ISSUE THREAD

**Issue by DraxJaster** [AmmeySaini/Edu-Mail-Generator#107]
Hey i use the Edu Email Generator in a rdp because i dont have a PC but in the past it works perfectly fine. But i use the 0.2.8 version because the proxy detected and its still doesnt work. I used it in a rdp.
![Uploading Screenshot_2021-08-21-12-06-26-82.png…]()

**Comment by Code-KaMyinn** [comment]
> Hey i use the Edu Email Generator in a rdp because i dont have a PC but in the past it works perfectly fine. But i use the 0.2.8 version because the proxy detected and its still doesnt work. I used it in a rdp.
> ![Screenshot_2021-08-21-12-06-26-82](https://user-images.githubusercontent.com/67590542/130311511-6ead95f0-f8bd-457f-afd2-be8a0d5338e8.png)

me too, i am also have the same problem
previously it work for me
now I try both window and linux 
can't fix
ERROR
A proxy connection has been detected. To connect to California Community Colleges you must disable anonymizing services. This may include:
Tor web browser
VPN connections
Anonymizing browser plugins

and the terminal show this message
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bot.py", line 1169, in <module>
    main()
  File "bot.py", line 1166, in main
    start_bot(start_url, userEmail, allColleges[userInput], userInput + 1, cookies, token)
  File "bot.py", line 126, in start_bot
    WebDriverWait(driver, 10).until(
  File "C:\Users\s'p'y\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\support\wait.py", line 87, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:

**Comment by MathewJake365** [comment]
Same here. Still doesn't work. Can you please fix this?
