### ISSUE TITLE
Trackback (most recent call last)

### ISSUE THREAD

**Issue by codefreak558** [AmmeySaini/Edu-Mail-Generator#109]
`Traceback (most recent call last):
  File "/home/codefreak/Documents/.BLACK/edu/Edu-Mail-Generator-0.2.8/bot.py", line 122, in start_bot
    WebDriverWait(driver, 10).until(
  File "/home/codefreak/Documents/.BLACK/edu/testenv/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 87, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:181:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.jsm:393:5
element.find/</<@chrome://remote/content/marionette/element.js:305:16

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/codefreak/Documents/.BLACK/edu/Edu-Mail-Generator-0.2.8/bot.py", line 1169, in <module>
    main()
  File "/home/codefreak/Documents/.BLACK/edu/Edu-Mail-Generator-0.2.8/bot.py", line 1166, in main
    start_bot(start_url, userEmail, allColleges[userInput], userInput + 1, cookies, token)
  File "/home/codefreak/Documents/.BLACK/edu/Edu-Mail-Generator-0.2.8/bot.py", line 126, in start_bot
    WebDriverWait(driver, 10).until(
  File "/home/codefreak/Documents/.BLACK/edu/testenv/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 87, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:181:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.jsm:393:5
element.find/</<@chrome://remote/content/marionette/element.js:305:16`

**Comment by karthik4569** [comment]
yea even i am getting the same error

**Comment by FeelsBadMan1** [comment]
You should take a better look on the Traceback. as ist says a Timeout error and the Traceback also point to a WebDriverWait function that is used to wait for a element to be loaded and avaible to be used by the bot. However this element could not be found after 10 seconds so a tiimeouterror became raised

**Comment by karthik4569** [comment]
> You should take a better look on the Traceback. as ist says a Timeout error and the Traceback also point to a WebDriverWait function that is used to wait for a element to be loaded and avaible to be used by the bot. However this element could not be found after 10 seconds so a tiimeouterror became raised

The proxy is actually getting detected by the website so it won't go past that so the whole thing doesn't work now
