### ISSUE TITLE
A proxy connection has been detected

### ISSUE THREAD

**Issue by ankityadavhere** [AmmeySaini/Edu-Mail-Generator#111]
Tried ```python setup.py``` but getting this error

Below are the logs

```bash
Traceback (most recent call last):
  File "D:\Edu-Mail-Generator-master\setup.py", line 72, in <module>
    main()
  File "D:\Edu-Mail-Generator-master\setup.py", line 25, in main
    firefox_ver = get_firefox_version()
  File "D:\Edu-Mail-Generator-master\__dwnldDrivers\versions.py", line 74, in get_firefox_version
    platform, _ = get_platform_architecture_firefox()
  File "D:\Edu-Mail-Generator-master\__dwnldDrivers\versions.py", line 51, in get_platform_architecture_firefox
    architecture = os_arch()
  File "D:\Edu-Mail-Generator-master\__dwnldDrivers\versions.py", line 30, in os_arch
    output = subprocess.check_output(['wmic', 'os', 'get', 'OSArchitecture'])
  File "C:\Python39\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Python39\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by ankityadavhere** [comment]
I manually downloaded the web driver so this error is solved but now I'm getting this proxy error

![Annotation 2021-09-09 142237](https://user-images.githubusercontent.com/83703777/132655235-a5448e02-8c06-4993-a08b-89dab026e4ec.png)

**Comment by ankityadavhere** [comment]
@AmmeySaini dude please respond!

**Comment by reedcrif** [comment]
You can close your issue as https://github.com/AmmeySaini/Edu-Mail-Generator/issues/101 exists
