### ISSUE TITLE
SyntaxError: future feature annotations is not defined

### ISSUE THREAD

**Issue by BangMbon** [AmmeySaini/Edu-Mail-Generator#129]
Traceback (most recent call last):
  File "bot.py", line 13, in <module>
    import seleniumwire.undetected_chromedriver.v2 as uc
  File "/usr/local/lib/python3.6/dist-packages/seleniumwire/undetected_chromedriver/__init__.py", line 2, in <module>
    import undetected_chromedriver as uc
  File "/usr/local/lib/python3.6/dist-packages/undetected_chromedriver/__init__.py", line 31, in <module>
    from . import v2
  File "/usr/local/lib/python3.6/dist-packages/undetected_chromedriver/v2.py", line 4
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined

![Screenshot_7](https://user-images.githubusercontent.com/45095797/145674972-9dd208c5-7a2c-4ec3-bec8-349f52a3d405.png)

**Comment by 30grand** [comment]
@scamizon on telegram I have edu accounts available for sale

**Comment by mo0haned** [comment]
I had the same issue when I used Python 2.6 environment. and it was fixed when I changed to 2.7. so I think we should follow the requirements
