### ISSUE TITLE
bot.py not working

### ISSUE THREAD

**Issue by Akane124** [AmmeySaini/Edu-Mail-Generator#142]
I ran setup.py, chose "2", and when I run bot.py runs, this error shows:

Traceback (most recent call last):
  File "C:\Users\alan_\Downloads\Edu-Mail-Generator-0.2.8\Edu-Mail-Generator-0.2.8\bot.py", line 7, in <module>
    from seleniumwire import webdriver
  File "C:\Users\alan_\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\seleniumwire\webdriver.py", line 14, in <module>
    from selenium.webdriver import TouchActions  # noqa
ImportError: cannot import name 'TouchActions' from 'selenium.webdriver' (C:\Users\alan_\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\__init__.py)

**Comment by iowayyed** [comment]
same issue

**Comment by mdmahinpro** [comment]
it's not working bro.
