### ISSUE TITLE
It closes automatically 

### ISSUE THREAD

**Issue by Crossbow-Killer** [AmmeySaini/Edu-Mail-Generator#155]
I installed the setup.py, but when I run the bot.py or helper.py, the command closes automatically.

**Comment by kabanla101** [comment]
*] Parsing Incap Cookies (success)
[*] Interceptor Addition (success)
[*] Injecting Incap CookiesTraceback (most recent call last):
  File "/home/fola/Desktop/Edu-Mail-Generator/bot.py", line 1169, in <module>
    main()
  File "/home/fola/Desktop/Edu-Mail-Generator/bot.py", line 1166, in main
    start_bot(start_url, userEmail, allColleges[userInput], userInput + 1, cookies, token)
  File "/home/fola/Desktop/Edu-Mail-Generator/bot.py", line 98, in start_bot
    driver.add_cookie(ck)
  File "/home/fola/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 1131, in add_cookie
    self.execute(Command.ADD_COOKIE, {'cookie': cookie_dict})
  File "/home/fola/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "/home/fola/.local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidCookieDomainException: Message: invalid cookie domain: Cookie 'domain' mismatch
  (Session info: chrome=100.0.4896.127)
Stacktrace:
#0 0x564fde29bad3 <unknown>
#1 0x564fddffb568 <unknown>
#2 0x564fde073446 <unknown>
#3 0x564fde04f5f2 <unknown>
#4 0x564fde062824 <unknown>
#5 0x564fde04f4e3 <unknown>
#6 0x564fde024d1a <unknown>
#7 0x564fde025e75 <unknown>
#8 0x564fde2c9efd <unknown>
#9 0x564fde2e319b <unknown>
#10 0x564fde2cbc65 <unknown>
#11 0x564fde2e3ec8 <unknown>
#12 0x564fde2bf360 <unknown>
#13 0x564fde2ffa68 <unknown>
#14 0x564fde2ffbe8 <unknown>
#15 0x564fde3197fd <unknown>
#16 0x7fa1c0c29d80 <unknown>
