### ISSUE TITLE
not working on linux

### ISSUE THREAD

**Issue by Fexaop** [AmmeySaini/Edu-Mail-Generator#160]
Firefox
Installed verision - 97.0
Latest geckodriver version - v0.31.0
Downloading...
[################################] 2652/2652 - 00:00:00
Download Successful

Chrome
Chrome isn't installed

Wich browser do you prefer to run script on

[*] 1 Firefox

Enter id ex - 1 or 2: 1
Setup Completed
╭─gunit at gunit in ⌁/Documents/Projects/Edu-Mail-Generator (master ✚1)
╰─λ python bot.py

 _____    _         __  __       _ _    ____
| ____|__| |_   _  |  \/  | __ _(_) |  / ___| ___ _ __
|  _| / _` | | | | | |\/| |/ _` | | | | |  _ / _ \ '_ \
| |__| (_| | |_| | | |  | | (_| | | | | |_| |  __/ | | |_
|_____\__,_|\__,_| |_|  |_|\__,_|_|_|  \____|\___|_| |_(_)
      Github Repo - https://git.io/JJisT/

[*] Select a college from all available colleges to proceed....

[*] 1 - MSJC College
[*] 2 - Contra Costa College
[*] 3 - City College
[*] 4 - Sacramento College
[*] 5 - Mt San Antonio

[*] Enter college id for ex - 1 or 2 or 3.... : 2

[*] Selected College: Contra Costa College

[*] Enter Your Email: gunit1895@gmail.com

[*] Performing Incapsula Bypass
[*] Fetching Token (success)
[*] Fetching Cookies (success)
[*] Sending Custom Fields and Token to Server (success)
[*] Setting Incap Token (success)
[*] Sending Custom Cookies (success)
[*] Parsing Incap Cookies (success)
[*] Interceptor Addition (success)
[*] Injecting Incap CookiesTraceback (most recent call last):
  File "/home/gunit/Documents/Projects/Edu-Mail-Generator/bot.py", line 1169, in <module>
    main()
  File "/home/gunit/Documents/Projects/Edu-Mail-Generator/bot.py", line 1166, in main
    start_bot(start_url, userEmail, allColleges[userInput], userInput + 1, cookies, token)
  File "/home/gunit/Documents/Projects/Edu-Mail-Generator/bot.py", line 98, in start_bot
    driver.add_cookie(ck)
  File "/home/gunit/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 1136, in add_cookie
    self.execute(Command.ADD_COOKIE, {'cookie': cookie_dict})
  File "/home/gunit/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "/home/gunit/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidCookieDomainException: Message: Cookies may only be set for the current domain (account.cccmypath.org)
Stacktrace:
WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:183:5
InvalidCookieDomainError@chrome://remote/content/shared/webdriver/Errors.jsm:323:5
cookie.add@chrome://remote/content/marionette/cookie.js:186:13
GeckoDriver.prototype.addCookie@chrome://remote/content/marionette/driver.js:1885:10

**Comment by Fexaop** [comment]
i m using archlinux and i get these error when i try to tun the bot.py
+ on firefox proxy error
+ i have chrome but it dont detect
