### ISSUE TITLE
selenium.common.exceptions.InvalidCookieDomainException: Message: invalid cookie domain: Cookie 'domain' mismatch

### ISSUE THREAD

**Issue by A-latte** [AmmeySaini/Edu-Mail-Generator#162]
•arSlng ncap 00 ies success 
•-vTools listening on ws://127.0.0.1:64416/devtools/browser/9ac71db3-fd22-420f-a3ea-b693a1827f5b [*] Interceptor Addition (success) [*] Injecting Incap CookiesTraceback (most recent call last): File "C:\Users\HP\Downloads\Edu-Mail-Generator-master\bot.py", line 1169, in <module> main() File "C:\Users\HP\Downloads\Edu-Mail-Generator-master\bot.py", line 1166, in main start_bot(start_url, userEmail, allColleges[userInput], userInput + 1, cookies, token) File "C:\Users\HP\Downloads\Edu-Mail-Generator-master\bot.py", line 98, in start_bot driver.add_cookie(ck) File "C:\Users\HP\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 742, in add_cookie self.execute(Command.ADD_COOKIE, {'cookie': cookie dirt}) File "C:\Users\HP\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 435, in execute self.error_handler. check_response(response) File "C:\Users\HP\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response raise exception_class(message, screen, stacktrace) selenium.common.exceptions.InvalidCookieDomainException: Message: invalid cookie domain: Cookie 'domain' mismatch (Session info: chrome=103.0.5060.134) tacktrace: Backtrace: Ordinal0 [0x010F5FD3+2187219] Ordinal0 [0x0108E6D1+1763025] Ordinal0 [0x00FA3E78+802424] Ordinal0 [0x01008961+1227105] Ordinal0 [0x0OFECB8C+1100684] Ordinal0 [0x0OFFCFC2+1167298] Ordinal0 [0x0OFEC9A6+1100198] Ordinal0 [0x0OFC6F80+946048] Ordinal0 [0x0OFC7E76+949878] GetHandleVerifier [0x013990C2+2721218] GetHandleVerifier [0x0138AAF0+2662384] GetHandleVerifier [0x0118137A+526458] GetHandleVerifier [0x01180416+522518] Ordinal0 [0x01094EAB+1789611] Ordinal0 [0x010997A8+1808296] Ordinal0 [0x01099895+1808533] Ordinal0 [0x010A26C1+1844929] BaseThreadInitThunk [0x7741FA29+25] RtlGetAppContainerNamedObjectPath [0x77917A9E+286] RtlGetAppContainerNamedObjectPath [0x77917A6E+238] 
![Screenshot 2022-07-29 082258](https://user-images.githubusercontent.com/109261782/181663819-c8a766c4-4f24-4389-9b82-003349dd600d.png)

Idk some how,this error happen when i run this bot : (.Pls help me :((

**Comment by qyopy** [comment]
i got the same problem

**Comment by Xyberonz** [comment]
same

**Comment by cdtian** [comment]
same

**Comment by Drewfulls** [comment]
same same, hoping it gets addressed, if funding would help, ask.

**Comment by Welding-Torch** [comment]
same

**Comment by Welding-Torch** [comment]
same problem
