### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by hoaug-tran** [AmmeySaini/Edu-Mail-Generator#163]
### I was try this bot but i got this error:
`Error - <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)>`

**Is there anyway to fix it? thank you.**

**Comment by hoaug-tran** [comment]
> Message that will be displayed on users first issue

I was solved this issues but i got new issues is:

```
[*] Injecting Incap CookiesTraceback (most recent call last):
  File "/Users/guaoh/Downloads/Edu-Mail-Generator-0.2.8/bot.py", line 1169, in <module>
    main()
  File "/Users/guaoh/Downloads/Edu-Mail-Generator-0.2.8/bot.py", line 1166, in main
    start_bot(start_url, userEmail, allColleges[userInput], userInput + 1, cookies, token)
  File "/Users/guaoh/Downloads/Edu-Mail-Generator-0.2.8/bot.py", line 98, in start_bot
    driver.add_cookie(ck)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 742, in add_cookie
    self.execute(Command.ADD_COOKIE, {'cookie': cookie_dict})
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 435, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidCookieDomainException: Message: invalid cookie domain: Cookie 'domain' mismatch
  (Session info: chrome=103.0.5060.134)
Stacktrace:
0   5900d9f65264cb31_chromedriver       0x000000010d213ef9 5900d9f65264cb31_chromedriver + 4480761
1   5900d9f65264cb31_chromedriver       0x000000010d19f5d3 5900d9f65264cb31_chromedriver + 4003283
2   5900d9f65264cb31_chromedriver       0x000000010ce32338 5900d9f65264cb31_chromedriver + 410424
3   5900d9f65264cb31_chromedriver       0x000000010cea8f16 5900d9f65264cb31_chromedriver + 896790
4   5900d9f65264cb31_chromedriver       0x000000010ce85a62 5900d9f65264cb31_chromedriver + 752226
5   5900d9f65264cb31_chromedriver       0x000000010ce984f1 5900d9f65264cb31_chromedriver + 828657
6   5900d9f65264cb31_chromedriver       0x000000010ce85953 5900d9f65264cb31_chromedriver + 751955
7   5900d9f65264cb31_chromedriver       0x000000010ce5bcd5 5900d9f65264cb31_chromedriver + 580821
8   5900d9f65264cb31_chromedriver       0x000000010ce5cd25 5900d9f65264cb31_chromedriver + 584997
9   5900d9f65264cb31_chromedriver       0x000000010d1e502d 5900d9f65264cb31_chromedriver + 4288557
10  5900d9f65264cb31_chromedriver       0x000000010d1ea1b3 5900d9f65264cb31_chromedriver + 4309427
11  5900d9f65264cb31_chromedriver       0x000000010d1ef23f 5900d9f65264cb31_chromedriver + 4330047
12  5900d9f65264cb31_chromedriver       0x000000010d1eadfa 5900d9f65264cb31_chromedriver + 4312570
13  5900d9f65264cb31_chromedriver       0x000000010d1c3fef 5900d9f65264cb31_chromedriver + 4153327
14  5900d9f65264cb31_chromedriver       0x000000010d204d78 5900d9f65264cb31_chromedriver + 4418936
15  5900d9f65264cb31_chromedriver       0x000000010d204eff 5900d9f65264cb31_chromedriver + 4419327
16  5900d9f65264cb31_chromedriver       0x000000010d21bab5 5900d9f65264cb31_chromedriver + 4512437
17  libsystem_pthread.dylib             0x00007fff203c48fc _pthread_start + 224
18  libsystem_pthread.dylib             0x00007fff203c0443 thread_start + 15
```

**Comment by Ngchpr** [comment]
help me 
C:\Users\ADMIN\Downloads\Compressed\Edu-Mail-Generator-master> python3 bot.py
Traceback (most recent call last):
  File "C:\Users\ADMIN\Downloads\Compressed\Edu-Mail-Generator-master\bot.py", line 7, in <module>
    from seleniumwire import webdriver
  File "C:\Users\ADMIN\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\seleniumwire\webdriver.py", line 27, in <module>
    from seleniumwire import backend, utils
  File "C:\Users\ADMIN\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\seleniumwire\backend.py", line 4, in <module>
    from seleniumwire.server import MitmProxy
  File "C:\Users\ADMIN\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\seleniumwire\server.py", line 5, in <module>
    from seleniumwire.handler import InterceptRequestHandler
  File "C:\Users\ADMIN\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\seleniumwire\handler.py", line 5, in <module>
    from seleniumwire import har
  File "C:\Users\ADMIN\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\seleniumwire\har.py", line 12, in <module>
    from seleniumwire.thirdparty.mitmproxy.http import HTTPFlow
  File "C:\Users\ADMIN\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\seleniumwire\thirdparty\mitmproxy\http.py", line 7, in <module>
    from seleniumwire.thirdparty.mitmproxy.net import http
  File "C:\Users\ADMIN\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\__init__.py", line 1, in <module>
    from seleniumwire.thirdparty.mitmproxy.net.http import http1, http2, multipart, status_codes
  File "C:\Users\ADMIN\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\http1\__init__.py", line 2, in <module>
    from .read import (connection_close, expected_http_body_size, read_body, read_request, read_request_head,
  File "C:\Users\ADMIN\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\http1\read.py", line 7, in <module>
    from seleniumwire.thirdparty.mitmproxy.net.http import (headers, request,
  File "C:\Users\ADMIN\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\request.py", line 8, in <module>
    from seleniumwire.thirdparty.mitmproxy.net.http import cookies, message, multipart
  File "C:\Users\ADMIN\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\message.py", line 6, in <module>
    from seleniumwire.thirdparty.mitmproxy.net.http import encoding
  File "C:\Users\ADMIN\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\encoding.py", line 12, in <module>
    import brotli
  File "C:\Users\ADMIN\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\brotli.py", line 8, in <module>
    import _brotli
ImportError: DLL load failed while importing _brotli: The specified module could not be found.

**Comment by laimumu** [comment]
> > > Message that will be displayed on users first issue
> > 
> > 
> > I was solved this issues but i got new issues is:
> > ```
> > [*] Injecting Incap CookiesTraceback (most recent call last):
> >   File "/Users/guaoh/Downloads/Edu-Mail-Generator-0.2.8/bot.py", line 1169, in <module>
> >     main()
> >   File "/Users/guaoh/Downloads/Edu-Mail-Generator-0.2.8/bot.py", line 1166, in main
> >     start_bot(start_url, userEmail, allColleges[userInput], userInput + 1, cookies, token)
> >   File "/Users/guaoh/Downloads/Edu-Mail-Generator-0.2.8/bot.py", line 98, in start_bot
> >     driver.add_cookie(ck)
> >   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 742, in add_cookie
> >     self.execute(Command.ADD_COOKIE, {'cookie': cookie_dict})
> >   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 435, in execute
> >     self.error_handler.check_response(response)
> >   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
> >     raise exception_class(message, screen, stacktrace)
> > selenium.common.exceptions.InvalidCookieDomainException: Message: invalid cookie domain: Cookie 'domain' mismatch
> >   (Session info: chrome=103.0.5060.134)
> > Stacktrace:
> > 0   5900d9f65264cb31_chromedriver       0x000000010d213ef9 5900d9f65264cb31_chromedriver + 4480761
> > 1   5900d9f65264cb31_chromedriver       0x000000010d19f5d3 5900d9f65264cb31_chromedriver + 4003283
> > 2   5900d9f65264cb31_chromedriver       0x000000010ce32338 5900d9f65264cb31_chromedriver + 410424
> > 3   5900d9f65264cb31_chromedriver       0x000000010cea8f16 5900d9f65264cb31_chromedriver + 896790
> > 4   5900d9f65264cb31_chromedriver       0x000000010ce85a62 5900d9f65264cb31_chromedriver + 752226
> > 5   5900d9f65264cb31_chromedriver       0x000000010ce984f1 5900d9f65264cb31_chromedriver + 828657
> > 6   5900d9f65264cb31_chromedriver       0x000000010ce85953 5900d9f65264cb31_chromedriver + 751955
> > 7   5900d9f65264cb31_chromedriver       0x000000010ce5bcd5 5900d9f65264cb31_chromedriver + 580821
> > 8   5900d9f65264cb31_chromedriver       0x000000010ce5cd25 5900d9f65264cb31_chromedriver + 584997
> > 9   5900d9f65264cb31_chromedriver       0x000000010d1e502d 5900d9f65264cb31_chromedriver + 4288557
> > 10  5900d9f65264cb31_chromedriver       0x000000010d1ea1b3 5900d9f65264cb31_chromedriver + 4309427
> > 11  5900d9f65264cb31_chromedriver       0x000000010d1ef23f 5900d9f65264cb31_chromedriver + 4330047
> > 12  5900d9f65264cb31_chromedriver       0x000000010d1eadfa 5900d9f65264cb31_chromedriver + 4312570
> > 13  5900d9f65264cb31_chromedriver       0x000000010d1c3fef 5900d9f65264cb31_chromedriver + 4153327
> > 14  5900d9f65264cb31_chromedriver       0x000000010d204d78 5900d9f65264cb31_chromedriver + 4418936
> > 15  5900d9f65264cb31_chromedriver       0x000000010d204eff 5900d9f65264cb31_chromedriver + 4419327
> > 16  5900d9f65264cb31_chromedriver       0x000000010d21bab5 5900d9f65264cb31_chromedriver + 4512437
> > 17  libsystem_pthread.dylib             0x00007fff203c48fc _pthread_start + 224
> > 18  libsystem_pthread.dylib             0x00007fff203c0443 thread_start + 15
> > ```
> 
> Please update google chrome to 104 version

104 version chrome  also has this problem

**Comment by hoaug-tran** [comment]
@laimumu so, can i downgrade version of chrome to fix?

**Comment by laimumu** [comment]
> 
It will have new issues, it will detect you as a proxy, it seems that this project is no longer managed and updated
