### ISSUE TITLE
I am getting this error from helper.py 

### ISSUE THREAD

**Issue by mistsaadi** [AmmeySaini/Edu-Mail-Generator#168]
Fetching TokenTraceback (most recent call last):
  File "C:\Python39\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\saadf\Downloads\Edu-Mail-Generator-master\bot.py", line 1169, in <module>
    main()
  File "c:\Users\saadf\Downloads\Edu-Mail-Generator-master\bot.py", line 1161, in main
    start_url, cookies, token = fg_lp._tryHarder()
  File "c:\Users\saadf\Downloads\Edu-Mail-Generator-master\helper.py", line 79, in _tryHarder
    token = self.getAuthToken()
  File "c:\Users\saadf\Downloads\Edu-Mail-Generator-master\helper.py", line 72, in getAuthToken
    js = res.json()
  File "C:\Python39\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by RobinLoxlyHood** [comment]
@mistsaadi same issue

**Comment by uzair004** [comment]
same issue looks like the bot has stopped working :( @AmmeySaini

**Comment by ttoshiro** [comment]
Still facing this issue
