### ISSUE TITLE
Error after registration on OpenCCC

### ISSUE THREAD

**Issue by drawix** [AmmeySaini/Edu-Mail-Generator#32]
``` python
Traceback (most recent call last):
  File "bot.py", line 1026, in <module>
    main()
  File "bot.py", line 1023, in main
    start_bot(reg_url, userEmail, allColleges[userInput], userInput + 1)
  File "bot.py", line 396, in start_bot
    element = driver.find_element_by_id('accountFormSubmit')
  File "/home/admin12/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/home/admin12/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/admin12/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/admin12/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id="accountFormSubmit"]

```

**Comment by diegodelmondes** [comment]
same here.

**Comment by AmmeySaini** [comment]
Can you explain the error in brief so that i can replicate the same and check for fixes

**Comment by AdhityaRimba** [comment]
![Screenshot_44](https://user-images.githubusercontent.com/47937950/100735936-9e94d680-3404-11eb-9f1f-6761e4d40a9e.png)

**Comment by AmmeySaini** [comment]
Which college ?

**Comment by AdhityaRimba** [comment]
all of the college

**Comment by AmmeySaini** [comment]
I think it's the issue at openccc panel end
