### ISSUE TITLE
  File "/home/snoozedev/Edu-Mail-Generator/__dwnldDrivers/versions.py", line 106, in get_chrome_version

### ISSUE THREAD

**Issue by snoozedesert** [AmmeySaini/Edu-Mail-Generator#34]
Chrome
Traceback (most recent call last):
  File "setup.py", line 70, in <module>
    main()
  File "setup.py", line 35, in main
    chrome_ver = get_chrome_version()
  File "/home/snoozedev/Edu-Mail-Generator/__dwnldDrivers/versions.py", line 106, in get_chrome_version
    platform, _ = get_platform_architecture_chrome()
  File "/home/snoozedev/Edu-Mail-Generator/__dwnldDrivers/versions.py", line 67, in get_platform_architecture_chrome
    raise RuntimeError('Could not determine chromedriver download URL for this platform.')
RuntimeError: Could not determine chromedriver download URL for this platform.

i'm using linux mint 32 bit, i'm can't install chrome on 32 bit architecture. But i'm using firefox browser.

**Comment by AmmeySaini** [comment]
Did script detected the chrome version installed on your os ?
