### ISSUE TITLE
Stuck at last school attend

### ISSUE THREAD

**Issue by iyantae245** [AmmeySaini/Edu-Mail-Generator#37]
Traceback (most recent call last):
  File "C:\Users\djdoolky76\Desktop\Edu-Mail-Generator-master-master\bot.py", line 1026, in <module>
    main()
  File "C:\Users\djdoolky76\Desktop\Edu-Mail-Generator-master-master\bot.py", line 1023, in main
    start_bot(reg_url, userEmail, allColleges[userInput], userInput + 1)
  File "C:\Users\djdoolky76\Desktop\Edu-Mail-Generator-master-master\bot.py", line 513, in start_bot
    WebDriverWait(driver, 60).until(
  File "C:\Users\djdoolky76\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by Quastor** [comment]
Same problem here can somebody try to fix this

**Comment by iyantae245** [comment]
hopefully, there's a fix on this in the future

**Comment by ReubenAboagye** [comment]
@iyantae245 [suggestive quick fix : https://github.com/AmmeySaini/Edu-Mail-Generator/issues/35#issuecomment-747894973](https://github.com/AmmeySaini/Edu-Mail-Generator/issues/35#issuecomment-747894973)

**Comment by AmmeySaini** [comment]
Fixed!! Ref - [here](https://github.com/AmmeySaini/Edu-Mail-Generator/commit/a18d3929eea47297b2a4e968ed022f4d6a9948cb)
