### ISSUE TITLE
selenium.common.exceptions.NoSuchElementException: Message: Could not locate element with index 3

### ISSUE THREAD

**Issue by Udyz** [AmmeySaini/Edu-Mail-Generator#40]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\EduMail-Generator-master\bot.py", line 1070, in <module>
    main()
  File "C:\Users\Administrator\Desktop\EduMail-Generator-master\bot.py", line 1067, in main
    start_bot(reg_url, userEmail, allColleges[userInput], userInput + 1)
  File "C:\Users\Administrator\Desktop\EduMail-Generator-master\bot.py", line 482, in start_bot
    dropdown_menu.select_by_index(random.randint(1, 7))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\select.py", line 103, in select_by_index
    raise NoSuchElementException("Could not locate element with index %d" % index)
selenium.common.exceptions.NoSuchElementException: Message: Could not locate element with index 3

**Comment by AmmeySaini** [comment]
Are you facing this issue on v0.2.6 ?

**Comment by hgcool20** [comment]
I also received the same error. Please help

**Comment by Udyz** [comment]
i was fixed by myself, and add bypass captcha
