### ISSUE TITLE
Windows setup.py firefox geckodriver download problem

### ISSUE THREAD

**Issue by mmuncan** [AmmeySaini/Edu-Mail-Generator#42]
Firefox
Installed verision - 84.0.2
Latest geckodriver version - v0.28.0
Downloading...
Traceback (most recent call last):
  File "setup.py", line 70, in <module>
    main()
  File "setup.py", line 29, in main
    setup_Firefox(firefox_ver)
  File "C:\Users\JAMy\OneDrive\Desktop\BOTz_Colleges_ProtonVPN\Edu-Mail-Generator-master_3\Edu-Mail-Generator-master\__dwnldDrivers\versions.py", line 241, in setup_Firefox
    dwnld_zip_file(dwnldLink, './webdriver')
  File "C:\Users\JAMy\OneDrive\Desktop\BOTz_Colleges_ProtonVPN\Edu-Mail-Generator-master_3\Edu-Mail-Generator-master\__dwnldDrivers\versions.py", line 188, in dwnld_zip_file
    with ZipFile(BytesIO(r.content)) as my_zip_file:
  File "C:\Users\JAMy\AppData\Local\Programs\Python\Python38-32\lib\zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "C:\Users\JAMy\AppData\Local\Programs\Python\Python38-32\lib\zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by lidistat67** [comment]
Hey. I also got this issue but running python setup.py instead of python3 resolved this. Try doing this.
