### ISSUE TITLE
traceback error

### ISSUE THREAD

**Issue by kingisawesome** [AmmeySaini/Edu-Mail-Generator#45]
[*] Account Progress - 1/3 (Success)
[*] Account Progress - 2/3 (Success)
[*] Please fill the captcha in webdriver to proceed further
[*] Captcha Solved, Executing Further
[*] Account Progress - 3/3 (Success)
[*] Account Created Successfully, Details saved in myccAcc.txt, Filling Application Form Now
[*] Details Progress - 1/8 (Success)
Traceback (most recent call last):
  File "C:\Users\Fletcher\bot.py", line 1026, in <module>
    main()
  File "C:\Users\Fletcher\bot.py", line 1023, in main
    start_bot(reg_url, userEmail, allColleges[userInput], userInput + 1)
  File "C:\Users\Fletcher\bot.py", line 513, in start_bot
    WebDriverWait(driver, 60).until(
  File "C:\Users\Fletcher\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by AmmeySaini** [comment]
Seems like you are using old version of this repo
Update it and try again
