### ISSUE TITLE
I got this error

### ISSUE THREAD

**Issue by PineappleBeer** [AmmeySaini/Edu-Mail-Generator#46]
```
Traceback (most recent call last):
  File "bot.py", line 1094, in <module>
    main()
  File "bot.py", line 1090, in main
    start_bot(reg_url, userEmail, allColleges[userInput], userInput + 1)
  File "bot.py", line 99, in start_bot
    driver.find_element_by_xpath(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="portletContent_u16l1n18"]/div/div[2]/div/a[2]"}
  (Session info: headless chrome=87.0.4280.141)
```
version: v0.2.6
please tell me how to solve it?
thanks : )

**Comment by PineappleBeer** [comment]
I modified the code
```
# For Chrome
        if typex == 'chrome':
            chrome_options = Options()
            chrome_options.add_argument('--headless')
            chrome_options.add_argument('--no-sandbox')
            chrome_options.add_argument('--disable-dev-shm-usage')
            driver = webdriver.Chrome(
                executable_path=r'./webdriver/chromedriver', options=chrome_options)
```
because if I don't modify it , i will get this error
```
Error - Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```
