### ISSUE TITLE
If chrome is not installed in windows, setup.py fails.

### ISSUE THREAD

**Issue by shivamsn97** [AmmeySaini/Edu-Mail-Generator#6]
OS: Windows 10
Browser: 
    Firefox: Installed
    Chrome: Not Installed
Error:
`Chrome
Traceback (most recent call last):
  File ".\setup.py", line 70, in <module>
    main()
  File ".\setup.py", line 35, in main
    chrome_ver = get_chrome_version()
  File "D:\Work\python\Edu-Mail-Generator\__dwnldDrivers\versions.py", line 120, in get_chrome_version
    version = process.communicate()[0].decode('UTF-8').strip().split()[-1]
IndexError: list index out of range`

**Comment by shivamsn97** [comment]
I have made a pull request (#7 ) to fix this issue.

**Comment by AmmeySaini** [comment]
Fixed with recent push
