### ISSUE TITLE
Script closes itself at firefox step

### ISSUE THREAD

**Issue by IshanAvasthi** [AmmeySaini/Edu-Mail-Generator#63]
Even though antivirus disabled

**Comment by AmmeySaini** [comment]
Can you provide more info on the error ?

**Comment by fahimscirex** [comment]
@AmmeySaini I'm having the same problem. Here's the error.
```
[*] Hold on Starting now, Keep checking this terminal for instructions
Traceback (most recent call last):
  File "/home/fahim/Git/edugen/bot.py", line 1040, in <module>
    main()
  File "/home/fahim/Git/edugen/bot.py", line 1037, in main
    start_bot(reg_url, userEmail, allColleges[userInput], userInput + 1)
  File "/home/fahim/Git/edugen/bot.py", line 90, in start_bot
    driver.find_element_by_xpath('//*[@id="portletContent_u16l1n18"]/div/div[2]/div/a[2]').click()
  File "/home/fahim/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/fahim/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/fahim/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/fahim/.local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //*[@id="portletContent_u16l1n18"]/div/div[2]/div/a[2]
```

**Comment by Upstream92** [comment]
I have the same problem :/ Has anyone found a solution?
![Captura de pantalla 2021-04-29 222937](https://user-images.githubusercontent.com/83442365/116649155-f3009b80-a93b-11eb-8145-3b4d94e10cd0.png)

**Comment by pacjo** [comment]
You can fix it by comenting out lines 24-32 AND 45-47, this worked for me with only chrome installed. I attach working [setup.py.txt](https://github.com/AmmeySaini/Edu-Mail-Generator/files/6538370/setup.py.txt) for chrome (change name to setup.py, because github doesn't allow python files as atachments).
