### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by HilFing-Real** [AmmeySaini/Edu-Mail-Generator#72]
When doing the application process 1/8
It crashes while filling the education section. after waiting for like 2 mins the bot crashes with this error :

```
Traceback (most recent call last):
  File "bot.py", line 1026, in <module>
    main()
  File "bot.py", line 1023, in main
    start_bot(reg_url, userEmail, allColleges[userInput], userInput + 1)
  File "bot.py", line 513, in start_bot
    WebDriverWait(driver, 60).until(
  File "/home/hilfing/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
```

Pls fix

**Comment by HilFing-Real** [comment]
Sorry forgot to update
