### ISSUE TITLE
Traceback Error (Setup)

### ISSUE THREAD

**Issue by Strafbefehl** [AmmeySaini/Edu-Mail-Generator#99]
Hey the setup doesn't work unfortunately always get this error

```
Firefox
Installed verision -
Latest geckodriver version - v0.29.1
Downloading...
Traceback (most recent call last):
  File "C:\Users\akhal\Desktop\Edu-Mail-Generator-master\setup.py", line 72, in <module>
    main()
  File "C:\Users\akhal\Desktop\Edu-Mail-Generator-master\setup.py", line 29, in main
    setup_Firefox(firefox_ver)
  File "C:\Users\akhal\Desktop\Edu-Mail-Generator-master\__dwnldDrivers\versions.py", line 246, in setup_Firefox
    dwnld_zip_file(dwnldLink, './webdriver')
  File "C:\Users\akhal\Desktop\Edu-Mail-Generator-master\__dwnldDrivers\versions.py", line 193, in dwnld_zip_file
    with ZipFile(BytesIO(r.content)) as my_zip_file:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\zipfile.py", line 1257, in __init__
    self._RealGetContents()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\zipfile.py", line 1324, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

**Comment by drhack00000** [comment]
Am getting errors in this part

Traceback (most recent call last):
  File "C:\Users\DRH Virtual Machine\AppData\Roaming\Python\Python310\site-packages\seleniumwire\undetected_chromedriver\__init__.py", line 2, in <module>
    import undetected_chromedriver as uc
  File "C:\Users\DRH Virtual Machine\AppData\Roaming\Python\Python310\site-packages\undetected_chromedriver\__init__.py", line 31, in <module>
    from . import v2
  File "C:\Users\DRH Virtual Machine\AppData\Roaming\Python\Python310\site-packages\undetected_chromedriver\v2.py", line 25, in <module>
    from .cdp import CDP
  File "C:\Users\DRH Virtual Machine\AppData\Roaming\Python\Python310\site-packages\undetected_chromedriver\cdp.py", line 6, in <module>
    from collections import Mapping, Sequence
ImportError: cannot import name 'Mapping' from 'collections' (C:\Program Files\Python310\lib\collections\__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\DRH Virtual Machine\Desktop\Edu-Mail-Generator-master\bot.py", line 13, in <module>
    import seleniumwire.undetected_chromedriver.v2 as uc
  File "C:\Users\DRH Virtual Machine\AppData\Roaming\Python\Python310\site-packages\seleniumwire\undetected_chromedriver\__init__.py", line 4, in <module>
    raise ImportError(
ImportError: undetected_chromedriver not found. Install it with `pip install undetected_chromedriver`.

**Comment by drhack00000** [comment]
**###AM GETTING ERRORS IN THIS PART###**

`Traceback (most recent call `last):`
File "C:\Users\DRH Virtual Machine\AppData\Roaming\Python\Python310\site-packages\seleniumwire\undetected_chromedriver_init_.py", line 2, in
import undetected_chromedriver as uc
File "C:\Users\DRH Virtual Machine\AppData\Roaming\Python\Python310\site-packages\undetected_chromedriver_init_.py", line 31, in
from . import v2
File "C:\Users\DRH Virtual Machine\AppData\Roaming\Python\Python310\site-packages\undetected_chromedriver\v2.py", line 25, in
from .cdp import CDP
File "C:\Users\DRH Virtual Machine\AppData\Roaming\Python\Python310\site-packages\undetected_chromedriver\cdp.py", line 6, in
from collections import Mapping, Sequence
ImportError: cannot import name 'Mapping' from 'collections' (C:\Program Files\Python310\lib\collections_init_.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "C:\Users\DRH Virtual Machine\Desktop\Edu-Mail-Generator-master\bot.py", line 13, in
import seleniumwire.undetected_chromedriver.v2 as uc
File "C:\Users\DRH Virtual Machine\AppData\Roaming\Python\Python310\site-packages\seleniumwire\undetected_chromedriver_init_.py", line 4, in
raise ImportError(
ImportError: undetected_chromedriver not found. Install it with pip install undetected_chromedriver.`
